# Form implementation generated from reading ui file '/Users/jannat.nayeem01gmail.com/Second Sem/Compilers/compiler_project/src/components/main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(408, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_text = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(60, 30, 113, 22))
        self.input_text.setObjectName("input_text")
        self.button_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(20, 60, 80, 22))
        self.button_1.setObjectName("button_1")
        self.button_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(110, 60, 80, 22))
        self.button_2.setObjectName("button_2")
        self.button_plus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_plus.setGeometry(QtCore.QRect(200, 60, 80, 22))
        self.button_plus.setObjectName("button_plus")
        self.button_multiply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_multiply.setGeometry(QtCore.QRect(250, 100, 80, 22))
        self.button_multiply.setObjectName("button_multiply")
        self.input_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.input_label.setGeometry(QtCore.QRect(20, 30, 57, 14))
        self.input_label.setObjectName("input_label")
        self.output_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(20, 110, 57, 14))
        self.output_label.setObjectName("output_label")
        self.output_lcd = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.output_lcd.setGeometry(QtCore.QRect(70, 100, 141, 23))
        self.output_lcd.setSmallDecimalPoint(True)
        self.output_lcd.setDigitCount(9)
        self.output_lcd.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.output_lcd.setProperty("value", 0.0)
        self.output_lcd.setProperty("intValue", 0)
        self.output_lcd.setObjectName("output_lcd")
        self.button_equal = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_equal.setGeometry(QtCore.QRect(290, 60, 80, 22))
        self.button_equal.setObjectName("button_equal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 408, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_multiply.setText(_translate("MainWindow", "*"))
        self.input_label.setText(_translate("MainWindow", "Input:"))
        self.output_label.setText(_translate("MainWindow", "Output:"))
        self.button_equal.setText(_translate("MainWindow", "="))
